[package]
name = "keyboard-layers-poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keyboard-events-processing = { path = "../keyboard-events-processing" }
